services:
  - type: web
    name: ml-api
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
