services:
  - type: web
    name: ml-api
    runtime: python
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "gunicorn app:app --workers=1"
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: "/opt/render/.cache/ms-playwright"