services:
  - type: web
    name: ml-scraper
    runtime: python
    buildCommand: |
      pip install --upgrade pip && 
      pip install -r requirements.txt && 
      playwright install --with-deps
    startCommand: gunicorn app:app --workers=1 --timeout 120
    envVars:
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/.cache/ms-playwright